name: chrishaueter.com
description: A blog on code and entrepreneurship.
markdown: redcarpet
permalink: /blog/:title
pygments: true
url: http://chrishaueter.com

sass:
  syntax: sass
  style: compressed

exclude: 
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
  - pip-log.txt
  - README.md
  - icebox
